openapi: 3.0.1
info:
  title: PuppeteerGPT
  description: A plugin to drive headless browser. You can use it to search, click, scroll or scrape on the web. You can automate any action just by chatting.
  version: "v1"
servers:
  - url: http://localhost:8008
paths:
  /visit:
    get:
      operationId: visit
      summary: Visit a website
      parameters:
        - in: query
          name: url
          schema:
            type: string
            enum: [back, forward, reload]
          required: true
          description: The url of the website to visit.
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /click:
    get:
      operationId: click
      summary: Click on a selector
      parameters:
        - in: query
          name: selector
          schema:
            type: string
          required: true
          description: The selector to click on
        - in: query
          name: xpath
          schema:
            type: boolean
          default: false
          description: Whether the selector is a xpath selector
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /observe:
    get:
      operationId: observe
      summary: Observe page body with XPath selector
      parameters:
        - in: query
          name: xpath
          schema:
            type: string
          required: true
          description: The xpath selector to observe
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /type:
    get:
      operationId: typeText
      summary: Type texts on a input field
      parameters:
        - in: query
          name: selector
          schema:
            type: string
          required: true
          description: The selector of the input field
        - in: query
          name: xpath
          schema:
            type: boolean
          default: false
          description: Whether the selector is a xpath selector
        - in: query
          name: text
          schema:
            type: string
          required: true
          description: The text to type
        - in: query
          name: pressEnter
          schema:
            type: boolean
          required: false
          default: true
          description: Whether to press enter after typing
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /router:
    get:
      operationId: router
      summary: Handle router
      parameters:
        - in: query
          name: action
          schema:
            type: string
            enum: [back, forward, reload]
          required: true
          description: The action to perform on the router
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /wait:
    get:
      operationId: wait
      summary: Wait for N seconds
      parameters:
        - in: query
          name: time
          schema:
            type: integer
          required: true
          description: Time to wait in seconds
      responses:
        "200":
          description: OK
        "404":
          description: Not found
  /exit:
    get:
      operationId: exit
      summary: Exit the browser
      responses:
        "200":
          description: OK
        "404":
          description: Not found
